### ISSUE TITLE
Reduce Top margin between navbar and hero

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#102]
## Describe the problem
The top margin between the navbar and the hero section on the website is too large, resulting in an unnecessary amount space at the top of the page. This creates an imbalance in the layout and detracts from the overall user experience.

## Solution
We would like to reduce the top margin between the navbar and the hero section to create a more balanced and visually appealing layout. By decreasing the amount of space at the top of the page, we can draw more attention to the content and make it easier for users to engage with the site.

**Comment by MOHDNEHALKHAN** [comment]
@FlavioAdamo  I want to work on this issue

**Comment by FlavioAdamo** [comment]
@MOHDNEHALKHAN  Sure!
Happy coding!

**Comment by MOHDNEHALKHAN** [comment]
![APIvault](https://user-images.githubusercontent.com/125626654/236418313-2bbe8bcd-aa78-40b9-a4fe-3e2a33e065d1.png)
@FlavioAdamo Please Check this screenshot if you like the changes then I will create a pull request.

**Comment by FlavioAdamo** [comment]
How much did you reduced the margin top?

**Comment by MOHDNEHALKHAN** [comment]
margin - top : 0

**Comment by FlavioAdamo** [comment]
I thinks its a little to much, how about a margin top of 4vw instead of 7vw?
Like this: 
![image](https://user-images.githubusercontent.com/46765573/236424617-d086a407-bcca-4f1b-8019-a94b3fac4ac2.png)

@MOHDNEHALKHAN What do you think?

**Comment by MOHDNEHALKHAN** [comment]
@FlavioAdamo  Can i create a PR for 4vw

**Comment by FlavioAdamo** [comment]
@MOHDNEHALKHAN  Of course you can!

**Comment by MOHDNEHALKHAN** [comment]
@FlavioAdamo Ok i will do it  Asap.

**Comment by gdjohn4s** [comment]
@MOHDNEHALKHAN Thank you so much but don't and take your time 😄
