### ISSUE TITLE
Open cards and repository links in new tabs

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#104]
## Is your feature request related to a problem? Please describe.
When I click on a Card or the Repository link in the sidebar menu, the page opens in the same tab, taking me away from the current page. This is not a good user experience.

## Describe the solution you'd like
I would like both the Cards and Repository links to open in a new tab, so that the user can easily return to the previous page.

**Comment by FlavioAdamo** [comment]
Of course! 
Happy coding!

**Comment by NirajD10** [comment]
any update?

**Comment by kotkaravishkar** [comment]
@NirajD10 I have made the required changes, but to check for cards, the backend is not running in local, so I stuck there.

**Comment by FlavioAdamo** [comment]
Hi @kotkaravishkar . You can use the production APIs without running the backend.

Just replace your .env file from this:
```env
VITE_APP_MODE=dev
VITE_API_VAULT_ENDPOINT=http://localhost:5001
```

to this
```env
VITE_APP_MODE=dev
VITE_API_VAULT_ENDPOINT=https://api.apivault.dev/
```

We are working on fixing the docker problem with Windows

**Comment by NirajD10** [comment]
I think we can close this issues
