### ISSUE TITLE
Automatically generate API list markdown

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#108]
**Is your feature request related to a problem? Please describe.**
The list of APIs in the [markdown](https://github.com/Exifly/ApiVault/tree/main/backend) file is static and manually updating it could be problematic.

**Describe the solution you'd like**
We need to create a python script to automatically generate a markdown with API ordered by category.

**Comment by gdjohn4s** [comment]
I think I've found a solution @FlavioAdamo .
Indeed, the script we prepared uses the **entries.json** file managed by the backend. But it's also true that the same data is returned by the /api/all endpoint.

At this point, we could adapt the script to make a GET request to the aforementioned endpoint and generate the markdown table from that data.

This way, it would also be dynamic and generate a table with the data directly from the repository and therefore updated.

Perhaps it could also be managed on the server's crontab or create a Github action that triggers when the **entries.json** file is modified, which will create a markdown table and call Github's API to open the PR with the updated table.

Let me know what you think.
