### ISSUE TITLE
The "TRENDING" title should not be visible on mobile

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#113]
## Describe the bug
The title "TRENDING" is visible on the mobile version, and it should be hidden.

##To Reproduce

1. Open the website on a mobile device.
2. Navigate to the homepage.
3. Observe that the title "TRENDING" is visible.

## Expected behavior
The title "TRENDING" should not be visible on the mobile version of the website.

Screenshots
![image](https://user-images.githubusercontent.com/46765573/236671251-a8a27324-8809-40a6-8261-c3137e11cd45.png)
Desktop
![image](https://user-images.githubusercontent.com/46765573/236671226-d83d75a7-9ff3-489d-a9a6-1e624cdcc2a0.png)

Smartphone

Device: [iPhone 12]
OS: [e.g. iOS 16.4]

## Additional context
This issue affects the mobile version of the website only. The title "TRENDING" should be hidden on the mobile version to provide a consistent user experience across all devices.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it

**Comment by gdjohn4s** [comment]
Sure, thank you!

**Comment by tarunsamanta2k20** [comment]
@gdjohn4s does it work?

![image](https://user-images.githubusercontent.com/55488549/236831524-56812560-26e2-465d-94d4-150914d36727.png)
