### ISSUE TITLE
Component causing horizontal scrolling on mobile version

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#114]
## Describe the bug
A component is adding too much right padding or margin in the mobile version, causing horizontal scrolling and a poor user experience.

## To Reproduce

1. Open the website on a mobile device.
2. Scroll to the left

## Expected behavior
The component should have appropriate padding and margin that fits within the screen width of the mobile device, and does not cause horizontal scrolling.

Screenshots
![image](https://user-images.githubusercontent.com/46765573/236671487-388f3a08-3b77-4f11-a85c-de5203579c60.png)

### Smartphone

Device: [e.g. iPhone SE]

## Additional context
The issue affects the mobile version of the website only. The component causing the issue needs to be identified and modified to have appropriate padding and margin for the mobile version.

**Comment by NirajD10** [comment]
I added PR. Please check
