### ISSUE TITLE
Misalignment of "Trending category" section and APIs section on Desktop version.

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#116]
## Describe the bug
The "Trending" category section is not aligned with the APIs section, causing a misalignment issue.

## To Reproduce
1. Open the website on any device.
2. Navigate to the homepage.
2. Observe the "Trending" category section and the APIs section.

##  Expected behavior
The "Trending" category section should be aligned with the API card section.

## Screenshots
![image](https://user-images.githubusercontent.com/46765573/236672484-fce35bc1-2f7e-4080-ae68-7b2f3c9f5a23.png)
Desktop

OS: [MacOs]
Browser: [Chrome]

## Additional context
This issue affects the desktop version of the website.

**Comment by tarunsamanta2k20** [comment]
I would like to work on it

**Comment by gdjohn4s** [comment]
Yeah of course, thank you!

**Comment by tarunsamanta2k20** [comment]
@gdjohn4s is it fine?
![image](https://github.com/Exifly/ApiVault/assets/55488549/15bfee1c-e60d-4e57-a79d-f25f19b49b3c)

**Comment by gdjohn4s** [comment]
@tarunsamanta2k20 The second one with RANDOM positioned on the left 😄
