### ISSUE TITLE
Change a link on footer for software version string

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#131]
## Is your feature request related to a problem? Please describe.
No, it's just a modification related to the user experience.

## Describe the solution you'd like
It would be more appropriate if the software version link points directly to the release changelog on the repository.

## Screenshot
<img width="526" alt="image" src="https://user-images.githubusercontent.com/19678157/236888511-3b89c9c5-9d23-459b-b8fb-cd00a2cd760d.png">

**Comment by Samcode001** [comment]
Can u please tell me what the problem

**Comment by gdjohn4s** [comment]
There is no problem, it's just a change of link on the footer when you click on the site version. However, a PR has been opened about this issue -> #132 .
