### ISSUE TITLE
Hover on sidebar element don't redirect on routes properly

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#134]
## Describe the bug
When hovering over an item in the sidebar, the associated link is only clickable if the mouse pointer passes over the text and not over the entire element itself.

### To Reproduce:
![Screen Recording 2023-05-09 at 15 58 29](https://github.com/Exifly/ApiVault/assets/19678157/132d049c-2ed9-4fb5-9a38-0b3ce0e669ca)

### Expected behavior:
The user should be able to click on any hover of the item on the sidebar and go to the desired address without necessarily having to hover over the text.

### Desktop (please complete the following information):
- Browser [Tested on: Safari, Brave, Edge]

**Comment by Badrnyali** [comment]
Hi, 
i wanted to work on this issue. Is it important to stay with ul > li structure. If so i think it can be implemented with the v-slot https://router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link .

**Comment by FlavioAdamo** [comment]
@Badrnyali Thanks for the interest!
Issue assigned.

May your code be bug-free and your coffee always hot! :)
