### ISSUE TITLE
 Increase font-size of description in Api Card

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#141]
## Is your feature request related to a problem? Please describe.

The font-size of the description text in the Api Card is currently a little too small, which makes it difficult to read on both desktop and mobile devices. This can be frustrating for users who need to quickly understand what the API does and how it can be used.

## Describe the solution you'd like

I would like to request an increase in the font-size of the description text in the Api Card. However, I understand that we need to find a good compromise so that the text is not too big and still remains readable on both desktop and mobile devices.

## Additional context

I've attached a screenshot of the current Api Card for reference. Thank you for considering this feature request.
![image](https://github.com/Exifly/ApiVault/assets/46765573/e541eba2-f88b-4f32-ae89-818aaf3cdca8)

**Comment by NirajD10** [comment]
i'll try this

**Comment by FlavioAdamo** [comment]
Thanks Niraj!

**Comment by FlavioAdamo** [comment]
@NirajD10 issue transferred to #152
