### ISSUE TITLE
Add animated gradient border effect to search bar

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#142]
## Is your feature request related to a problem? Please describe.

Currently, the search bar on our website lacks visual interest and could benefit from an additional design element to make it stand out more. Adding an animated gradient border effect to the search bar would not only make it more visually appealing, but it would also draw attention to the search bar and make it more likely for users to engage with it.

## Describe the solution you'd like

I would like to request the addition of an animated gradient border effect to the search bar, following the guide provided at https://www.julienthibeaut.xyz/blog/create-animated-gradient-borders-with-css. This effect would involve adding a gradient border to the search bar that would animate and change colors over time, creating a dynamic and eye-catching effect.

**Comment by FlavioAdamo** [comment]
Sure! 
Thanks for contributing!

**Comment by vizzv** [comment]
please assign me this issue.
I almost implement it.
Here is my implementation, also tell me preferred colors for animation.
my colors are: cyan, blue, magenta , red .


https://github.com/Exifly/ApiVault/assets/66671671/e2f19737-d38d-4bd8-8cb6-a33b9b488d53

**Comment by gdjohn4s** [comment]
i'm closing this issue as completed
