### ISSUE TITLE
Trending categories without border color

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#143]
## Is your feature request related to a problem? Please describe.
No, it's a modification related to the website interface to improve user experience.

## Describe the solution you'd like
We would like to remove the border from the trending categories.

## Screenshot
![Screenshot 2023-05-10 at 17 51 46](https://github.com/Exifly/ApiVault/assets/19678157/951384ec-19b1-4449-8689-f7ced94c4f2a)

What do you think? Is it better like this or with colored borders?

**Comment by HassanTanveer** [comment]
I think it looks better without the border.

I can help change it if you assign the issue to me.

**Comment by FlavioAdamo** [comment]
Sure!!
Thanks for helping!

**Comment by FlavioAdamo** [comment]
@HassanTanveer I just saw your profile, I'm a Django developer too! Actually I'm working on migrating the project from flask to django. So having other django developers on the team makes me even happier about the migration!

**Comment by HassanTanveer** [comment]
I'll be happy to help with the migration

Btw, what was the reason to migrate to django from flask?

**Comment by FlavioAdamo** [comment]
We just created a [discord](https://discord.gg/79SaysSd6C) server, if you want to join we can discuss there

https://discord.gg/79SaysSd6C

**Comment by HassanTanveer** [comment]
I've joined :)
