### ISSUE TITLE
[APIFT]

### ISSUE THREAD

**Issue by nickatnight** [Exifly/ApiVault#145]
### API Information
API Name: MaaS | Musk as a Service
Description: API to fetch random news articles which mention Elon Musk
Category: News
What Auth is used (ex: Api Key): None
HTTPS: true
CORS: false
Api Link: https://elonmu.sh/api

### Why we should Integrate your api on our listing?
It's a free satirical api I made for fun. Open source too if anyone wants an intro to a real wold ExpressJS app https://github.com/nickatnight/elonmu.sh.

**Comment by FlavioAdamo** [comment]
@nickatnight Review passed!
The API is now available!
