### ISSUE TITLE
Implement a "load more" button in the random APIs page

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#147]
## Is your feature request related to a problem? Please describe.

As a user of the website, I would like to be able to see more than just 9 random APIs on the homepage. It would be helpful to have a "load more" button at the bottom of the page that, when clicked, would add 9 new random APIs to the list.

## Describe the solution you'd like

I would like to see a "load more" button at the bottom of the APIVAULT homepage. When clicked, this button would use the endpoint in `randomApis.js` to dynamically load 9 new random APIs and add them to the bottom of the existing list. The button would continue to load additional APIs as long as they are available.

To use the local server your .env file in the `frontend` folder should look like  this:
```env
VITE_APP_MODE=dev
VITE_API_VAULT_ENDPOINT=http://localhost:5001
```

The functon to call the api you need is `getApiData` inside `randomApis.js`.

If you need more information feel free to ping me on this issue

**Comment by et-c** [comment]
I'd like to work on this issue

**Comment by FlavioAdamo** [comment]
@et-c Sure, happy coding!
If you need help feel free to reach me!

**Comment by gdjohn4s** [comment]
sure! thanks
