### ISSUE TITLE
Adjust the website to the top 

### ISSUE THREAD

**Issue by dperdomog** [Exifly/ApiVault#149]
**Before** 
![image](https://github.com/Exifly/ApiVault/assets/43431933/23d440fc-ced0-4498-85fc-c2ae49c961ef)

**After**
![after](https://github.com/Exifly/ApiVault/assets/43431933/be4eeda5-43cf-49b9-a734-a149a1ab2730)

**Is your feature request related to a problem? Please describe.**
Is not considered a problem.

**Describe the solution you'd like**
I think the website could benefit from moving content higher since it will create more space and look better in my opinion.

**Additional context**
This is my first time doing this so i apologize in advance if i did something wrong. Cheers

**Comment by gdjohn4s** [comment]
@dperdomog 
I really like it with the tight spacing. Maybe I would add a couple of pixels between the various components, but otherwise, it's okay. 
If you want, I can assign you the issue.

Thank you.

**Comment by gdjohn4s** [comment]
@dperdomog 
I really like it with the tight spacing. Maybe I would add a couple of pixels between the various components, but otherwise, it's okay. 
If you want, I can assign you the issue.

Thank you.

**Comment by HassanTanveer** [comment]
@gdjohn4s Please assign this to me, if @dperdomog doesn't want it ofc

**Comment by FlavioAdamo** [comment]
@HassanTanveer If he doesn't reply to us within 24h from the date of publication of the post, it will be assigned to you right away!

**Comment by HassanTanveer** [comment]
Sounds good :)

**Comment by dperdomog** [comment]
Hello guys, you can assign this to @HassanTanveer , im still learning and i don't want to mess something up, thanks and im happy to make a contribution, thanks!

**Comment by gdjohn4s** [comment]
@HassanTanveer any updates?

**Comment by HassanTanveer** [comment]
Will create the PR today

**Comment by gdjohn4s** [comment]
Ok, thank you
