### ISSUE TITLE
Adjust Font Size in API Card for Improved Readability

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#152]
## Is your feature request related to a problem? Please describe.

The text in the API card is too big and impacts the overall user experience.

## Describe the solution you'd like

I would like the font size in the API card to be adjusted to around 15px. This will ensure that the text is more legible and users can easily comprehend the information presented.

## Additional context

Attached are screenshots showcasing the current oversized text in the API card, which causes readability issues. Adjusting the font size to around 15px would greatly enhance the user experience and make the information more accessible

<img width="1091" alt="image" src="https://github.com/Exifly/ApiVault/assets/46765573/7c2e377a-6b99-4283-aca6-439bf527098a">

**Comment by realrohitgurav** [comment]
I've made a PR for this issue, can you kindly review it? :)

**Comment by NirajD10** [comment]
Well, sorry for late. I guess someone made it :) +1
