### ISSUE TITLE
Add new key icon on card attributes for auth type

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#162]
## Describe the solution you'd like
I believe that the icon in question is more suitable for indicating the type of authentication used in the APIs.

## Screenshot
![Screenshot 2023-05-15 at 13 11 40](https://github.com/Exifly/ApiVault/assets/19678157/4543aee9-db77-4a8e-8ce4-af0a5a3c4965)

## Technical details
The icon should be [faKey](https://fontawesome.com/icons/key?f=classic&s=solid)

**Comment by Razaik25** [comment]
Is this issue up for grabs? Can look into it if it is.

**Comment by NirajD10** [comment]
I think we should implement of this new icon. I like it

**Comment by gdjohn4s** [comment]
i'll assign this issue to @Razaik25.
thank you!
