### ISSUE TITLE
Improve the vue-router pages and layouts to not load everytime a user click on some links

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#163]
## Is your feature request related to a problem? Please describe.
Yes. The problem is quite evident when, for example, I click on a category from the homepage, the page completely reloads. This behavior is not correct as both the navbar and the sidebar should remain fixed while only the content on the right, such as the cards, should change. With this fix, not only will the site's performance be optimized, but also fewer requests will be made to the backend or external services. Additionally, it would eliminate redundancy across various pages.

## Describe the solution you'd like
A good solution would be to abstract the layout that contains both the Navbar and the Sidebar and ensure that the vue-router only changes the content present in the ContentBody.

## Describe alternatives you've considered
I haven't found any other alternatives so far. If you have any, feel free to share them on this issue.

**Comment by DomeT99** [comment]
Hello!
I agree with your idea, it's the best solution.
It's possible extract the navabr, sidebar, ecc in a component call default.vue in the layout folder, right?

**Comment by DomeT99** [comment]
No worries, I'm here for anything
