### ISSUE TITLE
Hover effect doesn't work on light mode on Trending Categories

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#164]
## Describe the bug
When hovering over the trending categories in light mode, the hover effect is not visible.

## To Reproduce
1. Go to apivault.dev
2. Hover over the trending categories.

## Expected behavior
I should be able to clearly see the hover effect.

## Screenshots
https://github.com/Exifly/ApiVault/assets/19678157/08ff081b-3b05-4a5f-b2b7-f7185f3dc6b9

## Desktop (please complete the following information):
- Browser: [all]

**Comment by DomeT99** [comment]
HI!
I tried to reproduce this bug, but the problem is that the color of the `hover` property is very similar to the base color. 
Therefore, it is imperceptible.
The feature works fine.

**Comment by DomeT99** [comment]
Okay, I could open a PR to resolve this problem later, no worries.
