### ISSUE TITLE
change theme mode button into a toggle

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#166]
## Is your feature request related to a problem? Please describe
No, there isn't problems with theme mode button, but i believe is better using a toggle to switch from light to dark.
This issue thread can be using as a discussion to discuss for alternatives.

## Describe the solution you'd like
The solution i had in mind is like this screenshot. When toggle is triggered it switch color scheme.
Like this:
<img width="257" alt="image" src="https://github.com/Exifly/ApiVault/assets/19678157/2f12cf34-b61b-4427-b1b3-8f19d7dfd671">

## Additional context
If you have better ideas feel free to write here.

**Comment by vishal7738639800** [comment]
hey @gdjohn4s  would you like to elaborate more about the problem

**Comment by gdjohn4s** [comment]
hi @vishal7738639800 
there isn't no problem with this issue, just a modification to the theme button switcher

**Comment by Badrnyali** [comment]
hi @vishal7738639800 
i'm also interested about this issue. You can pass it to me if you don't want it )

**Comment by FlavioAdamo** [comment]
@vishal7738639800 We would like to replace the dark mode/light mode button with a switch.
If you don't want to work on this issue we will assign it to @Badrnyali .

Thanks in advance to both of you <3

**Comment by Manuel-Suarez-Abascal** [comment]
@gdjohn4s @FlavioAdamo do we want to use the switch toggle with custom CSS code or do you have any recommendation for a Vue's switch toggle component?

**Comment by gdjohn4s** [comment]
@Manuel-Suarez-Abascal Vuetify framework has a **Switch** component but i think it's better to create our own for now (just to avoid implementing a single component of a large framework).
I found a  [codepen](https://codepen.io/mburnette/details/LxNxNg) for a complete CSS switch, what do you think about?

**Comment by cyberGHostJs** [comment]
hi, i worked on replacing the theme mode button with a toggle  on a different branch and this is what it looks like now.
![Screen Shot 2023-05-17 at 9 58 26 AM](https://github.com/Exifly/ApiVault/assets/105425922/80a30cff-df0e-4917-9517-980e1c5fea8b)

![Screen Shot 2023-05-17 at 9 58 40 AM](https://github.com/Exifly/ApiVault/assets/105425922/344f7af7-95e5-4667-8163-09a077dd48cd)
 you can merge it if you're okay with it. or point out what you'd like me to adjust.

**Comment by gdjohn4s** [comment]
@cyberGHostJs thank you so much! we'll review your PR soon.
