### ISSUE TITLE
Hero is not centered on Category pages

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#173]
## Describe the bug
My issue is as follows:
When I click on a category from the sidebar menu, the text on the hero is not aligned to the left but gets shifted to the center.
![image](https://github.com/Exifly/ApiVault/assets/19678157/f828cd9e-4fd8-41f2-a927-811c71bf8ce5)

## To Reproduce
1. Click on a category on sidebar menu

## Expected behavior
![image](https://github.com/Exifly/ApiVault/assets/19678157/151b26a1-f852-4693-9e01-d60a78719a04)

## Desktop (please complete the following information):
 - Browser [all]

**Comment by Taseeeer** [comment]
Hey @gdjohn4s, can you assign me this issue, I'd like to work on it.
