### ISSUE TITLE
Highlight the clicked page category

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#174]
## Describe the bug
The problem is as follows:
When I click on a category, I would like to know on which page I am. To achieve this, I would like to see the hover effect on the category within the sidebar menu.

## Expected behavior
![Screenshot 2023-05-23 at 15 47 33](https://github.com/Exifly/ApiVault/assets/19678157/b6c8b812-3ce9-4f52-8f69-c66d09f564cf)

## Desktop (please complete the following information):
- Only on desktop

**Comment by HassanTanveer** [comment]
Hey, I would like to work on this issue

**Comment by Taseeeer** [comment]
Hi @gdjohn4s, I can work on this issue.

**Comment by gdjohn4s** [comment]
Hey guys.
I'll assign this issue to @HassanTanveer because the issue #173 is already assigned to @Taseeeer 

Thank you!

**Comment by Taseeeer** [comment]
@gdjohn4s if theres no update on this, I can still work on this issue.
