### ISSUE TITLE
Redirect on category page when I click on the category badge on the card

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#176]
## Describe the bug
I wouldn't define it as a bug, but it's definitely a problem for the user experience. It would be very convenient if I could also directly navigate to the category of the selected API from the card by clicking on the subtitle of the card.

## Expected behavior
![Screenshot 2023-05-24 at 15 37 40](https://github.com/Exifly/ApiVault/assets/19678157/3b8a43a1-2e46-454d-8096-bcd6d81cf949)
When I hover over the card and click on the subtitle containing the API category, I should be taken to the page that displays all the APIs in that category.

**Comment by Taseeeer** [comment]
@gdjohn4s at this time the whole card is clickable and you cannot hover on the category explicitly, do you want to change this behaviour and wants the category - in this case "Music" to be clickable and it navigates you to its page in the categories?

**Comment by gdjohn4s** [comment]
Yes, if you turn the category into a `<NuxtLink>`, the whole card remain clickable but if you put your mouse on the category badge and click on it, you'll redirect on the category page of the card.

**Comment by Taseeeer** [comment]
I can work on this, assign it to me.

**Comment by gdjohn4s** [comment]
of course! thank you 😄
