### ISSUE TITLE
Not HTTPS text is wrapped on mobile devices.

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#185]
## Describe the bug
The text of APIs that are not in HTTPS is not displayed on a single line.
This issue only occurs on mobile devices.

## Expected behavior
The text should be displayed without wrapping to a new line.

## Screenshots
![2023-05-26 19 29 47](https://github.com/Exifly/ApiVault/assets/19678157/0cc5d8e3-c10b-40ed-9533-c772de8aaf3b)

**Comment by Taseeeer** [comment]
hi @gdjohn4s I can work on this, assign it to me.

**Comment by gdjohn4s** [comment]
ok @Taseeeer thanks!
