### ISSUE TITLE
[APIFT]

### ISSUE THREAD

**Issue by leinaht** [Exifly/ApiVault#209]
### API Information
API Name: Pittsburgh Regional Transit BusTime API
Description: Pittsburgh Regional Transit bus and light rail arrival times and route information using Clever Devices BusTime API
Category: Transportation
What Auth is used (ex: Api Key): API Key
HTTPS: true
CORS: false
Api Link: https://realtime.portauthority.org/bustime/api/v3

### Why we should Integrate your api on our listing?

I see other regional transit systems and wanted to add my local one as well!

**Comment by gdjohn4s** [comment]
we are checking this api, future updates are coming.

**Comment by gdjohn4s** [comment]
@leinaht your API has been added. thank you! 😄
