### ISSUE TITLE
[APIFT]

### ISSUE THREAD

**Issue by SebastjanPrachovskij** [Exifly/ApiVault#248]
### API Information
API Name: SearchApi
Description: Real-time Google and other search engines results API
Category: Development
What Auth is used (ex: Api Key): Api Key
HTTPS: true 
CORS: false
Api Link: https://www.searchapi.io/

### Why we should Integrate your api on our listing?

- Supports precise location geo-targeting
- Uses only premium US-based proxies
- Structures Google (Search, News, Jobs, Shopping and other services) results into JSON in real-time (~2 seconds)
- US-Legal scraping protection
- Has a free plan

**Comment by gdjohn4s** [comment]
Hi @SebastjanPrachovskij !
You should use the submit api modal on our website as we dismissed the submit using the github issues.

Thank you for your patience and for submitting your API 😄

**Comment by gdjohn4s** [comment]
Close as completed
