### ISSUE TITLE
[ FEATURE ] set API max retry

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#262]
## Is your feature request related to a problem? Please describe
No, but for a possible future problem like DDOS.

## Describe the solution you'd like
I'd like to set a max retry per user session. 

## Additional context
This is a possible way to implement it in **settings.py:**
```python
'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
```

**Comment by Dev79844** [comment]
Hey @gdjohn4s! I would like to work on this issue.

**Comment by FlavioAdamo** [comment]
hI @Dev79844 , sure!
I think a good limit would be 100 requests per hour for users not logged in, and 1000 for logged in users.

@gdjohn4s wdyt?

**Comment by gdjohn4s** [comment]
sure

**Comment by Dev79844** [comment]
@gdjohn4s I am getting this error while setting up the application locally. Can help me?
<img width="1792" alt="Screenshot 2023-09-21 at 2 44 04 PM" src="https://github.com/Exifly/ApiVault/assets/51128342/e7c28621-67b2-4507-a3f3-2d42b14b0802">

**Comment by gdjohn4s** [comment]
@Dev79844 Try removing the versioning and use only `distro-info` in the requirements
