### ISSUE TITLE
[ ENHANCEMENT ] Set debug boolean value on .env file

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#266]
## Is your feature request related to a problem? Please describe
Not a problem at all, but it's a good practice to set the debug value inside the .env file

## Describe the solution you'd like
Set the debug configuration inside .env file like
`DEBUG=True`

## Describe alternatives you've considered
If someone have a valid alternative, please share it with us 😃

**Comment by vaibh27** [comment]
Hey @gdjohn4s, I would like to the changes regarding this one, Can you assign it to me ?

**Comment by gdjohn4s** [comment]
Sure @vaibh27 , thanks for your help 😃

**Comment by vaibh27** [comment]
Hello @gdjohn4s,

I've noticed that there are three environment (env) files in our project. I'd like to confirm whether we should include the 'debug' boolean value only in the env file located in the main directory? 

Thank you.

**Comment by vaibh27** [comment]
Hello @gdjohn4s,

I've noticed that there are three environment (env) files in the project. I'd like to confirm that we only have to add the 'debug' boolean value, in the env file located in the main directory?

Thank you.

**Comment by gdjohn4s** [comment]
Hi @vaibh27
Yes but in the main backend directory.

This is the structure:
- Apivault root
  - .env -> This is for docker compose
- backend
  - .env -> this handle the backend environment variables for django
- frontend
  - .env -> this handle the frontend environment variables for nuxt.js
