### ISSUE TITLE
Input field need gap for desktop version

### ISSUE THREAD

**Issue by NirajD10** [Exifly/ApiVault#270]
## Describe the bug
In 'Submit your api' modal, there is no gap between name and auth input field.

## Expected behavior
make a gap such as margin or padding.

## Screenshots
![image](https://github.com/Exifly/ApiVault/assets/66014487/d0483c0f-ea29-4359-b613-557a28b812c1)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser: Chrome
 - Version: lastest version

**Comment by Sky-De** [comment]
@NirajD10 hi, i would like to contribute to your project and this is good start point, assign this to me
Thanks

**Comment by FlavioAdamo** [comment]
@Sky-De sure! Thanks for the interest
@NirajD10 Thanks for opening the issue :)

**Comment by Sky-De** [comment]
@FlavioAdamo Hi there. There seems to have been a misunderstanding on my part. I quickly looked into the project before requesting the assignment and mistakenly thought it was a Next.js project. However, after installing the app, I realized that it is actually a Nuxt.js project with Python as the backend. Unfortunately, I do not have enough experience with Nuxt.js, and I am personally not interested in it. While I could try to search, learn, and fix the issue, it would take up a lot of time. Instead, I believe that this issue would be a great opportunity for those who are working or learning Nuxt.js or Vue js. Therefore, I am unassigning myself from this issue. I hope you understand and have a great day. 
Thank you

**Comment by DomeT99** [comment]
Hello guys!
I opened a PR to fix this issue :)
