### ISSUE TITLE
The search icon in the searchbar is not centered

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#42]
**Describe the bug**
The search icon in the searchbar is not centered

**To Reproduce**
1. Open the website using the mobile view

**Screenshots**
![Mqr4GGP](https://user-images.githubusercontent.com/46765573/234880849-fbe45eeb-d3bb-46e4-aaf6-819ac50d21c4.png)

**Smartphone :**
 - Device: [Iphone 12]
 - OS: [Ios 16]
 - Browser [safarii]

**Comment by NirajD10** [comment]
Check PR
