### ISSUE TITLE
Improve navbar UX

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#44]
**Is your feature request related to a problem? Please describe.**
[hsiwoenfhsopwon15](https://www.reddit.com/user/hsiwoenfhsopwon15/) on reddit
The nav bar is a bad ux imo - it opens all the way to the edge of the screen.

**Describe the solution you'd like**
Solution : Have the nav bar 75% wide with a slight blur in the background to make the nav stand out more

**Describe alternatives you've considered**
Of course you can propose any solution you like

**Comment by kiabq** [comment]
Hey, I'd definitely pick this issue up. I was looking through the code for the nav bar and saw a few issues. Particularly with the CSS. Along with fixing the nav bar, I feel like the contents of the page take up a lot of room on the page. This is especially noticeable on larger screens.

**Comment by MichaelBelgium** [comment]
A full width navbar isn't bad, altho some navbar buttons are hidden for me: https://i.imgur.com/2MsBpdh.png
I only can see "stars" button

**Comment by gdjohn4s** [comment]
Yeah, the full width on larger screen seems to be buggy.

![image](https://user-images.githubusercontent.com/19678157/235301004-765495dc-dab6-4e40-8812-884c8d90dbae.png)

As you can see, the media query for larger screen have a margin-left

**Comment by gdjohn4s** [comment]
I am closing the issue as resolved for PR #46 . Thank you 😄
