### ISSUE TITLE
Hamburger menu on mobile doesn't go all the way down

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#45]
**Describe the bug**
As [sbmo](https://www.reddit.com/user/sbmo/) said on Reddit, there's a small bug on mobile, on the hamburger menu overlay thing: scrolling to the bottom doesn't go all the way down

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19678157/235301568-076addf5-eea3-47aa-8ad1-da180d87731b.png)

**Smartphone:**
 - Device: All
 - OS: all
 - Browser All

**Comment by NirajD10** [comment]
I think this issues has been solved. Can we try to stop overflow background when we are in mobile menu (in mobile view)?

**Comment by NirajD10** [comment]
as another issues, when we are responsive mode(mobile view), by clicking dark or white mode button they change position of list. maybe we should disable animation(only mobile view) and add background color when we click one of menu items.


https://user-images.githubusercontent.com/66014487/235316273-97fc77c9-8379-48a1-8f07-dbfd6fc0a6bd.mp4

**Comment by Raheemshah2809** [comment]
Could change it to a toggle?

**Comment by FlavioAdamo** [comment]
> as another issues, when we are responsive mode(mobile view), by clicking dark or white mode button they change position of list. maybe we should disable animation(only mobile view) and add background color when we click one of menu items.
> 
>  animation.disable.in.mobile.view.mp4

Thanks for report , i think that we should open another Issue for that :)

**Comment by FlavioAdamo** [comment]
> Could change it to a toggle?
> 
> 

Not a bad idea actually, we will definitely consider this in a future version

**Comment by gdjohn4s** [comment]
I'll work on this fix 😄

**Comment by gdjohn4s** [comment]
I'm closing this issue as solved with PR #70
