### ISSUE TITLE
[APIFT]

### ISSUE THREAD

**Issue by bandemer** [Exifly/ApiVault#47]
### API Information
API Name: DigiDates.de
Description: Open Rest API for various date and time calculations
Category: Calendar
What Auth is used (ex: Api Key): none
HTTPS: true
CORS: true
Api Link: https://digidates.de/en/

### Why we should Integrate your api on our listing?
Its free and hopefully useful

**Comment by gdjohn4s** [comment]
Thank you for requesting to add your API. 
We will update you as soon as we have tested and added it to the project.

**Comment by gdjohn4s** [comment]
Hi @bandemer, I tried your APIs and found them very useful. 
They also work well, we'll add them to APIVault.
