### ISSUE TITLE
Report Button on API

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#51]
### Describe the solution you'd like
This feature will allow users to report an API for various reasons such as: API not working, offensive API, etc.

### The concept is as follows:
![image](https://user-images.githubusercontent.com/19678157/235312257-c7e9fcbe-ee77-44bf-a905-f31236f41214.png)

### Logic
We were thinking of using GitHub issue templates to open an issue with the reason reported from the website.
When a user clicks on the icon, it opens a GitHub issue in another browser window, selecting a specific template for the report.

### Why this feature?
The main reason is to filter APIs in order to ensure that the resources displayed on APIVault are genuine and functional.

**Comment by NirajD10** [comment]
I'll do this feature.

**Comment by NirajD10** [comment]
check the video if it's satisfied this feature, then I'll try to PR.

https://user-images.githubusercontent.com/66014487/235708065-2e43e566-f144-4827-9363-103b213933e4.mp4

**Comment by Mohit269** [comment]
Maybe we can add a dialogue box which contains a field with api name and url, and send the report to the main admin email.

**Comment by gdjohn4s** [comment]
this feature will be on standby for now due to some reasons that we will release shortly in an announcement. 
thank you for your patience.
