### ISSUE TITLE
Menu list on mobile devices clicking weird animation

### ISSUE THREAD

**Issue by NirajD10** [Exifly/ApiVault#58]
**Describe the bug**
 when we are responsive mode(mobile view), by clicking dark or white mode button they change position of list. 

**Expected behavior**
disable animation(only mobile view) and add background color when we click one of menu items.

**Screenshots**

https://user-images.githubusercontent.com/66014487/235337547-601a2e70-6f12-4313-9177-1cd22785f30e.mp4

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All

**Comment by FlavioAdamo** [comment]
@NirajD10 @gdjohn4s 
Something like this?
![navbar](https://user-images.githubusercontent.com/46765573/235375358-34654515-8cb2-4c74-bfcf-16215e1b56be.gif)

**Comment by gdjohn4s** [comment]
@FlavioAdamo oh i like this hover effect 🙂. But i dont think it will solve the mobile issue btw

**Comment by NirajD10** [comment]
@FlavioAdamo Yeah but in mobile view we can add active pseudo classes instead of hover.  and disable scale animation

**Comment by iamjamesfrancis** [comment]
Hi @NirajD10, 
Please review the video below and confirm if that is what you want.
https://user-images.githubusercontent.com/55175085/235754126-3638ee52-d3d1-4160-8cc0-4fe09864274f.mp4

**Comment by NirajD10** [comment]
@iamjamesfrancis nice one. one more thing, does it work when you click one of list categories? 

by the way you can do it PR, the moderator will check code.

**Comment by FlavioAdamo** [comment]
@iamjamesfrancis  Good job!
A few things to make it even look better:
- Add a border radius to the hover effect
- save the background hover variable in the style.css

When you are ready we will review the PR

**Comment by iamjamesfrancis** [comment]
Hi all,
Thank you for your feedback.

@NirajD10, I added the same styling for categories as well.

@FlavioAdamo, Sure with those requirements I will create the PR before 22:00 IST. 😊

**Comment by FlavioAdamo** [comment]
@iamjamesfrancis Thanks you! Take your time, even if it takes you a couple of day don't worry!

**Comment by gdjohn4s** [comment]
Yeah and thank you so much 🙂
