### ISSUE TITLE
Clearing card api list when search input is not found.

### ISSUE THREAD

**Issue by NirajD10** [Exifly/ApiVault#59]
**Is your feature request related to a problem? Please describe.**
Currently, whenever the search input  is not found. we get no found title but the list is still there. so the people get confused whether the list is still there when search input is not found.

**Describe the solution you'd like**
When the search input is not found, we may remove cards. but if the search are correctly, the output list will be display.

**Comment by NirajD10** [comment]
I'll do this work.

**Comment by gdjohn4s** [comment]
Okay, I'll assign you to the issue then.
Thanks!
