### ISSUE TITLE
Contributors route didn't appear in mobile view

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#61]
**Describe the bug**
On mobile, the route to the contributor page is not displayed.

**To Reproduce**
1. Click on the Hamburger menu

**Expected behavior**
The link to the contributor page should appear correctly under the Menu along with the other options.

**Screenshots**
![image](https://user-images.githubusercontent.com/19678157/235383137-ed1ad415-08f6-4cb4-a7d8-4595dc23fcaa.jpeg)

**Smartphone:**
 - Device: iPhone 13 Mini
 - Browser: Safari, Edge, Brave

**Comment by kotkaravishkar** [comment]
@gdjohn4s Can i work on it ?

**Comment by FlavioAdamo** [comment]
@kotkaravishkar Of course you can!

**Comment by gdjohn4s** [comment]
I'm closing this issue as completed.
