### ISSUE TITLE
no links on mobile nav "Repository" and "Sponsor" items

### ISSUE THREAD

**Issue by kiabq** [Exifly/ApiVault#68]
**Problem**
Currently, there is no link for the "Repository" and "Sponsor" options in the mobile nav bar.

**Solution**
Add links to the "Repository" and "Sponsor" nav items in the mobile nav dropdown.

I've already made a PR because I feel it's a simple fix.

**Screenshots**
"Repository" and "Sponsor" options below in mobile navbar.
![temp](https://user-images.githubusercontent.com/44178907/235561346-c0e1e823-c1ac-4156-a07b-8272db23179b.png)

**Comment by gdjohn4s** [comment]
I'm closing this issue as completed.
