### ISSUE TITLE
BACKEND - Implement a "Trending categories" endpoint

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#82]
## Is your feature request related to a problem? Please describe.
As a user of the APIVAULT website, I would like to be able to see a list of the top 10 trending categories of APIs. This would help me to discover new APIs that are popular among other users and would be useful for my projects.

## Describe the solution you'd like
I would like to see a new API endpoint added to the APIVAULT backend that returns a list of the top 10 trending categories. For now, this API can simply read a static file called "trending_categories.json" that contains the top 10 categories, but later we can implement a more complex system that tracks API usage and updates the trending categories dynamically.

The endpoint should be a GET request to a URL like "/api/category/trending". The response should be a JSON object with the following structure:
```json
{
    "trending_categories": [
        {
            "category_name": "Blockchain",
            "api_count": 250
        },
        {
            "category_name": "Anime",
            "api_count": 200
        },
        ...
    ]
}

```
The category_name field should contain the name of the category, and the api_count field should contain the number of APIs in that category.

**Additional context**

**Comment by shubhamprateek** [comment]
Could you highlight which file in your code contains the other API definitions ?

**Comment by FlavioAdamo** [comment]
Yes of course. The other API definitions are is in backand>data>entries.json

Here -> https://github.com/Exifly/ApiVault/blob/main/backend/data/entries.json

**Comment by NirajD10** [comment]
well it need to make implement trending categories when people get upvote almost 2-4week, then the code need update json file for trending categories.

**Comment by FlavioAdamo** [comment]
Hey @shubhamprateek are you working on this issue? If yes i will assign it to you :)

**Comment by JayeshJanyani** [comment]
@FlavioAdamo As per the ask, please help me if I am wrong.
We are looking for an endpoint that will return the list of trending categories by reading the "trending_categories.json" file.
Please correct me if I am wrong.
Could you please help me with the below mentioned queries and assign the issue to me?

Questions:
1. Will we be manually updating the "trending_categories.json" file?
2. How frequently will we be updating the file?

**Comment by FlavioAdamo** [comment]
Exactly. The file is static and will be update manually for now by a moderator, in the near future we will implement an upvote system to the APIs. Based on the upvotes we will dynamical change the trending categories.

For now we just need an API that return the manually inserted trending categories.

If you need any more help feel free to reach me

**Comment by shubhamprateek** [comment]
@FlavioAdamo , I will start working on this issue.

**Comment by shubhamprateek** [comment]
Hi @FlavioAdamo , I have created a PR. Please review. 
[](https://github.com/Exifly/ApiVault/pull/105)
