### ISSUE TITLE
Add contributors link in the footer

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#94]
**Is your feature request related to a problem? Please describe.**
Remove "Coded by [gdjohn4s ](https://github.com/gdjohn4s)& [flavioad](https://github.com/FlavioAdamo)" In the footer.

**Describe the solution you'd like**
The new text will be "Coded by those[ wonderful people ](https://apivault.dev/contributors)"

**Comment by kotkaravishkar** [comment]
@FlavioAdamo  Can i work on it ?

**Comment by FlavioAdamo** [comment]
@kotkaravishkar  Sure!
Happy coding!
