### ISSUE TITLE
Cards on website not having the same height

### ISSUE THREAD

**Issue by FlavioAdamo** [Exifly/ApiVault#95]
**Describe the bug**
The cards on the website are not displaying at the same height, resulting in an uneven appearance of the layout.

**To Reproduce**
1. Click on the 'CALENDAR' category
2. The bug is visible in the first row

**Expected behavior**
The cards on the same row should display at the same height, creating an even appearance of the layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/46765573/236178642-175f2062-55dc-4f57-88fd-84e87dc43893.png)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [edge]

**Comment by iamjamesfrancis** [comment]
Hi @FlavioAdamo ,
Can I work on this issue?

**Comment by FlavioAdamo** [comment]
@iamjamesfrancis Sure!
Happy coding :)

**Comment by iamjamesfrancis** [comment]
@FlavioAdamo ,

**Bug Fixed** 😍

![image](https://user-images.githubusercontent.com/55175085/236258514-a272caa6-c138-4908-98b6-11705db8c1a5.png)

**Comment by gdjohn4s** [comment]
@iamjamesfrancis  Well done! Thanks 😄 
Please open a PR so that we can also test the fix.
